use std::{
    fs::File,
    io::{BufRead, BufReader},
    path::Path,
};

use colored::Colorize;

pub fn init_env() {
    let exists = Path::new(".env.example").exists();

    if exists {
        println!("{}", "file exists, overwrite? (y/n) ");

        let mut input = String::new();
        std::io::stdin().read_line(&mut input).unwrap();

        if input.trim().to_lowercase() != "y" {
            return;
        }
    }

    let file = File::open(".env").expect("Could not find .env file");
    let reader = BufReader::new(file);

    let mut content: String = String::from("# DevGuard autogenerated .env.example\n");

    for line in reader.lines() {
        let line = line.unwrap();
        if line.chars().count() == 0 {
            continue;
        }
        if line.starts_with("#") {
            content = format!("{content}\n{}", line);
            continue;
        }

        match line.trim().split_once("=") {
            Some((key, _)) => {
                content = format!("{content}\n{}=", key);
            }
            None => {
                println!(
                    "{}",
                    format!("⚠️  '{}' is malformed - skipping", line.trim()).yellow()
                );
            }
        }
    }

    std::fs::write(".env.example", content).expect("Could not write content to .env.example");
}
